
name: "it4065c_platform"
version: "1.0"
config-version: 2

profile: "it4065c_platform"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  it4065c_platform:
    staging:
      materialized: view
    core:
      materialized: table
    marts:
      materialized: table
