it4065c_platform:
  target: dev
  outputs:
    dev:
      type: postgres
      user: postgres
      password: "Pa$$w0rd123!"
      host: localhost
      port: 5432
      dbname: it4065c
      schema: student_kofi
      threads: 2
      sslmode: prefer
