it4065c_platform:
  target: dev
  outputs:
    dev:
      type: postgres
      user: "{{ env_var('IT4065C_DB_USER') }}"
      password: "{{ env_var('IT4065C_DB_PASSWORD') }}"
      host: "{{ env_var('IT4065C_DB_HOST', 'localhost') }}"
      port: "{{ env_var('IT4065C_DB_PORT', '5432') | int }}"
      dbname: "{{ env_var('IT4065C_DB_NAME', 'it4065c') }}"
      schema: "{{ env_var('IT4065C_DB_SCHEMA', 'student') }}"
      threads: 2
      sslmode: prefer
